    @if (Session::has('success') && ($message = Session::get('success')))
        <script>
            iziToast.success({
                id: null,
                class: '',
                title: '',
                titleColor: 'green',
                titleSize: '',
                titleLineHeight: '',
                message: '{{ $message }}',
                messageColor: '',
                messageSize: '',
                messageLineHeight: '',
                backgroundColor: '',
                theme: 'light', // dark
                color: 'green', // blue, red, green, yellow
                icon: 'ico-success',
                iconText: '',
                iconColor: '#fff',
                iconUrl: null,
                image: '',
                imageWidth: 50,
                maxWidth: null,
                zindex: null,
                layout: 1,
                balloon: false,
                close: true,
                closeOnEscape: false,
                closeOnClick: false,
                displayMode: 0, // once, replace
                position: 'bottomRight', // bottomRight, bottomLeft, topRight, topLeft, topCenter, bottomCenter, center
                target: '',
                targetFirst: true,
                timeout: 50000,
                rtl: false,
                animateInside: true,
                drag: true,
                pauseOnHover: true,
                resetOnHover: false,
                progressBar: true,
                progressBarColor: '',
                progressBarEasing: 'linear',
                overlay: false,
                overlayClose: false,
                overlayColor: 'rgba(0, 0, 0, 0.6)',
                transitionIn: 'fadeInUp',
                transitionOut: 'fadeOut',
                transitionInMobile: 'fadeInUp',
                transitionOutMobile: 'fadeOutDown',
                buttons: {},
                inputs: {},
                onOpening: function() {},
                onOpened: function() {},
                onClosing: function() {},
                onClosed: function() {}
            });
        </script>
    @elseif(Session::has('error') && ($message = Session::get('error')))
        <script>
            iziToast.error({
                id: null,
                class: '',
                title: '',
                titleColor: 'red',
                titleSize: '',
                titleLineHeight: '',
                message: '{{ $message }}',
                messageColor: '',
                messageSize: '',
                messageLineHeight: '',
                backgroundColor: '',
                theme: 'light', // dark
                color: 'red', // blue, red, green, yellow
                icon: 'ico-error',
                iconText: '',
                iconColor: '#fff',
                iconUrl: null,
                image: '',
                imageWidth: 50,
                maxWidth: null,
                zindex: null,
                layout: 1,
                balloon: false,
                close: true,
                closeOnEscape: false,
                closeOnClick: false,
                displayMode: 0, // once, replace
                position: 'bottomRight', // bottomRight, bottomLeft, topRight, topLeft, topCenter, bottomCenter, center
                target: '',
                targetFirst: true,
                timeout: 50000,
                rtl: false,
                animateInside: true,
                drag: true,
                pauseOnHover: true,
                resetOnHover: false,
                progressBar: true,
                progressBarColor: '',
                progressBarEasing: 'linear',
                overlay: false,
                overlayClose: false,
                overlayColor: 'rgba(0, 0, 0, 0.6)',
                transitionIn: 'fadeInUp',
                transitionOut: 'fadeOut',
                transitionInMobile: 'fadeInUp',
                transitionOutMobile: 'fadeOutDown',
                buttons: {},
                inputs: {},
                onOpening: function() {},
                onOpened: function() {},
                onClosing: function() {},
                onClosed: function() {}
            });
        </script>
    @elseif(Session::has('warning') && ($message = Session::get('warning')))
        <script>
            iziToast.warning({
                id: null,
                class: '',
                title: '',
                titleColor: 'yellow',
                titleSize: '',
                titleLineHeight: '',
                message: '{{ $message }}',
                messageColor: '',
                messageSize: '',
                messageLineHeight: '',
                backgroundColor: '',
                theme: 'light', // dark
                color: 'yellow', // blue, red, green, yellow
                icon: 'ico-warning',
                iconText: '',
                iconColor: '#fff',
                iconUrl: null,
                image: '',
                imageWidth: 50,
                maxWidth: null,
                zindex: null,
                layout: 1,
                balloon: false,
                close: true,
                closeOnEscape: false,
                closeOnClick: false,
                displayMode: 0, // once, replace
                position: 'bottomRight', // bottomRight, bottomLeft, topRight, topLeft, topCenter, bottomCenter, center
                target: '',
                targetFirst: true,
                timeout: 50000,
                rtl: false,
                animateInside: true,
                drag: true,
                pauseOnHover: true,
                resetOnHover: false,
                progressBar: true,
                progressBarColor: '',
                progressBarEasing: 'linear',
                overlay: false,
                overlayClose: false,
                overlayColor: 'rgba(0, 0, 0, 0.6)',
                transitionIn: 'fadeInUp',
                transitionOut: 'fadeOut',
                transitionInMobile: 'fadeInUp',
                transitionOutMobile: 'fadeOutDown',
                buttons: {},
                inputs: {},
                onOpening: function() {},
                onOpened: function() {},
                onClosing: function() {},
                onClosed: function() {}
            });
        </script>
    @elseif(Session::has('info') && ($message = Session::get('info')))
        <script>
            iziToast.info({
                id: null,
                class: '',
                title: '',
                titleColor: '#333',
                titleSize: '',
                titleLineHeight: '',
                message: '{{ $message }}',
                messageColor: '',
                messageSize: '',
                messageLineHeight: '',
                backgroundColor: '',
                theme: 'light', // dark
                color: '#fff', // blue, red, green, yellow
                icon: 'ico-info',
                iconText: '',
                iconColor: '#fff',
                iconUrl: null,
                image: '',
                imageWidth: 50,
                maxWidth: null,
                zindex: null,
                layout: 1,
                balloon: false,
                close: true,
                closeOnEscape: false,
                closeOnClick: false,
                displayMode: 0, // once, replace
                position: 'bottomRight', // bottomRight, bottomLeft, topRight, topLeft, topCenter, bottomCenter, center
                target: '',
                targetFirst: true,
                timeout: 50000,
                rtl: false,
                animateInside: true,
                drag: true,
                pauseOnHover: true,
                resetOnHover: false,
                progressBar: true,
                progressBarColor: '',
                progressBarEasing: 'linear',
                overlay: false,
                overlayClose: false,
                overlayColor: 'rgba(0, 0, 0, 0.6)',
                transitionIn: 'fadeInUp',
                transitionOut: 'fadeOut',
                transitionInMobile: 'fadeInUp',
                transitionOutMobile: 'fadeOutDown',
                buttons: {},
                inputs: {},
                onOpening: function() {},
                onOpened: function() {},
                onClosing: function() {},
                onClosed: function() {}
            });
        </script>
    @elseif(Session::has('status') && ($message = Session::get('status')))
        <script>
            iziToast.show({
                id: null,
                class: '',
                title: '',
                titleColor: '#fff',
                titleSize: '',
                titleLineHeight: '',
                message: '{{ $message }}',
                messageColor: '',
                messageSize: '',
                messageLineHeight: '',
                backgroundColor: '',
                theme: 'light', // dark
                color: '#8cfc03', // blue, red, green, yellow
                icon: 'ico-success',
                iconText: '',
                iconColor: '#8cfc03',
                iconUrl: null,
                image: '',
                imageWidth: 50,
                maxWidth: null,
                zindex: null,
                layout: 1,
                balloon: false,
                close: true,
                closeOnEscape: false,
                closeOnClick: false,
                displayMode: 0, // once, replace
                position: 'bottomRight', // bottomRight, bottomLeft, topRight, topLeft, topCenter, bottomCenter, center
                target: '',
                targetFirst: true,
                timeout: 50000,
                rtl: false,
                animateInside: true,
                drag: true,
                pauseOnHover: true,
                resetOnHover: false,
                progressBar: true,
                progressBarColor: '',
                progressBarEasing: 'linear',
                overlay: false,
                overlayClose: false,
                overlayColor: 'rgba(0, 0, 0, 0.6)',
                transitionIn: 'fadeInUp',
                transitionOut: 'fadeOut',
                transitionInMobile: 'fadeInUp',
                transitionOutMobile: 'fadeOutDown',
                buttons: {},
                inputs: {},
                onOpening: function() {},
                onOpened: function() {},
                onClosing: function() {},
                onClosed: function() {}
            });
        </script>
    @endif
